swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /product/AddProduct:
    post:
      tags:
      - product
      description: create product
      operationId: ProductController.AddProduct
      parameters:
      - in: body
        name: body
        description: body for product content
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Status'
        "403":
          description: body is empty
  /product/purchases:
    post:
      tags:
      - product
      description: buy product
      operationId: ProductController.Purchases product
      parameters:
      - in: body
        name: body
        description: body for purchase
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/models.PurchaseOrder'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Status'
        "403":
          description: body not found
        "422":
          description: not enough stock
definitions:
  models.Product:
    title: Product
    type: object
    properties:
      ProductID:
        type: integer
        format: int64
      Quatity:
        type: integer
        format: int64
  models.PurchaseOrder:
    title: PurchaseOrder
    type: object
    properties:
      ProductID:
        type: integer
        format: int64
      Quatity:
        type: integer
        format: int64
  models.Status:
    title: Status
    type: object
    properties:
      Successful:
        type: boolean
tags:
- name: product
  description: |
    ProductController  Operations about Product
